name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asteriskiry/static-analysis
      credentials:
        username: ${{ secrets.gh_user }}
        password: ${{ secrets.gh_token }}

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to github packages
        run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.gh_token }}' > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run check-formatting
      - name: Check types
        run: npm run check-types
      - name: Run linting
        run: npm run lint

      - name: Test that app builds
        run: npm run build
