name: Integration tests

on:
  push:
    branches: ['develop', 'feature/keycloak']
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106

    services:
      keycloak:
        image: ghcr.io/asteriskiry/keycloak
        credentials:
          username: ${{ secrets.gh_user }}
          password: ${{ secrets.gh_token }}
        ports:
          - 9090:8080

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to github packages
        run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.gh_token }}' > ~/.npmrc

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: REACT_APP_KEYCLOAK_URL=http://keycloak:9090
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
